### ISSUE TITLE
Unable to import into zabbix 6.4.1

### ISSUE THREAD

**Issue by elyograg** [vaniacer/Zabbix-Template-OS-Linux-ssh#1]
This template will not import into zabbix 6.4.1 (latest release as I write this).

This is the error message it shows:

```
    Error in query [INSERT INTO dashboard_page (dashboard_pageid,dashboardid,name,display_period,sortorder) VALUES ('65','92','','0','0')] [Duplicate entry '65' for key 'dashboard_page.PRIMARY'] [zabbix.php:22 → require_once() → ZBase->run() → ZBase->processRequest() → CController->run() → CControllerPopupImport->doAction() → CApiWrapper->__call() → CFrontendApiWrapper->callMethod() → CApiWrapper->callMethod() → CFrontendApiWrapper->callClientMethod() → CLocalApiClient->callMethod() → CConfiguration->import() → CConfigurationImport->import() → CConfigurationImport->processTemplateDashboards() → CTemplateDashboardImporter->import() → CTemplateDashboard->create() → CDashboardGeneral->updatePages() → DB::insert() → DB::insertBatch() → DBexecute() → trigger_error() in include/db.inc.php:367]
    SQL statement execution has failed "INSERT INTO dashboard_page (dashboard_pageid,dashboardid,name,display_period,sortorder) VALUES ('65','92','','0','0')".
```

I was unable to determine why this is a problem.  I don't know much about zabbix templates.

**Comment by vaniacer** [comment]
I've tried to import into v. 6.0+ it works.
![изображение](https://user-images.githubusercontent.com/18072680/232746309-7fc32d07-2f51-451f-b31b-08bf06c02cdd.png)

So I've reexported it and added to this repo:
https://github.com/vaniacer/Zabbix-Template-OS-Linux-ssh/blob/master/template_6.0%2B.yaml

**Comment by elyograg** [comment]
I have the same problem with that template as I had with the one that was already in the project.  I am running the most recent version of Zabbix - 6.4.1.

**Comment by elyograg** [comment]
![image](https://user-images.githubusercontent.com/4984827/232954000-a6d6f0f3-de8a-4b2e-82a8-8dd3460ca873.png)

**Comment by vaniacer** [comment]
Looks like you are trying to overwrite template or something like that. Make sure it's not imported already or maybe there is another template with the same name?

**Comment by elyograg** [comment]
There is only one template matching "ssh" and it's not this template.
![image](https://user-images.githubusercontent.com/4984827/235327835-afb6064d-905b-45ec-be48-ad1bdedddc85.png)
